version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cloud_uq_forum
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet
  myphp:
    build: 
      context: ./assignment/php
    restart: always
    expose:
      - 9000
    volumes:
      - ./assignment:/var/www/html
    depends_on:
      - mysql
    networks:
      - mynet
  mynginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./assignment:/var/www/html
      - ./assignment/nginx.ini:/etc/nginx/conf.d/default.conf
    depends_on:
      - myphp
    networks:
      - mynet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
